name: Python application

on:
  push:
    branches: main
  pull_request:
    branches: main
	
jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
		    sudo apt update -y
        sudo apt install python3-virtualenv
		    sudo apt install python3-pip
		    sudo apt install nginx -y
		    sudo apt install supervisor -y
		
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create Virtualenv
      run: |
        virtualenv env
		    source env/bin/activate
	
	- name: Run App
      run: |
        python project1/app.py
