name: Python Application
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ec2-13-234-67-156.ap-south-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        runs-on: self-hosted
        script: whoami
