name: Python application
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Install Packages
     - run: |
        sudo apt update -y && sudo apt install nginx python3-virtualenv python3-pip supervisor -y
     - name: Set up Python 3.8
       with:
        python-version: 3.8
     - name: Create Virtualenv
       run: |
        virtualenv env && source env/bin/activate
     - name: Run App
       run: |
        python project1/app.py
